
version: '3.8'

services:
  superclaude-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - COINGECKO_PRO_API_KEY=${COINGECKO_PRO_API_KEY}
      - DEFILLAMA_PRO_API_KEY=${DEFILLAMA_PRO_API_KEY}
      - VELO_API_KEY=${VELO_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - superclaude-app
    restart: unless-stopped

volumes:
  redis_data:
